
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: ebs-claim
  containers:
    - name: busy-container
      image: busybox:latest
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]

      volumeMounts:
        - name: ebs-volume
          mountPath: /data
